name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          pip install pipenv
      - name: data fetcher
        run: |
          pipenv run python data_fetcher.py
      - name: Commit files
        run: |
          git config --global user.name 'IncioMan'
          git config --global user.email 'incio_man@live.com'
          git add .
          git commit -am "Automated data fetching"
          git push
      - run: echo "🍏 This job's status is ${{ job.status }}."